apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: {{ .Values.cowabungaai.package.name }}
spec:
  sso:
    - name: CowabungaAI
      description: Client for logging into Supabase
      clientId: {{ .Values.cowabungaai.sso.clientId }}
      redirectUris:
        {{- range $.Values.cowabungaai.sso.redirectUris }}
        - {{ tpl . $ }}
        {{- end }}
      webOrigins:
        {{- range $.Values.cowabungaai.sso.webOrigins }}
        - {{ tpl . $ }}
        {{- end }}
  network:
    expose:
      - service: supabase-kong
        podLabels:
          app.kubernetes.io/name: {{ .Values.cowabungaai.package.name }}
          app.kubernetes.io/component: {{ .Values.cowabungaai.package.component }}
        host: {{ .Values.cowabungaai.package.host }}
        gateway: tenant
        port: 80
    allow:
      - direction: Ingress
        remoteGenerated: Anywhere
      - direction: Egress
        remoteGenerated: Anywhere
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: {{ .Values.cowabungaai.package.name }}
          app.kubernetes.io/component: {{ .Values.cowabungaai.package.component }}
        remoteGenerated: Anywhere
