Business Source License 1.1

Changes effective as of January 1, 2025

The Business Source License (this document, or the "License") is not an Open
Source license.  However, the Licensed Work will eventually be made available
under an Open Source License, as stated in this License.

License text copyright (c) 2025 CowabungaAI

For Business Source License 1.1, see https://mariadb.com/bsl11.

----------------------------------------------------------------------------

Business Source License 1.1

License text copyright (c) 2025 MariaDB Corporation Ab, All Rights Reserved.
"Business Source License" is a trademark of MariaDB Corporation Ab.

Terms

The Licensor hereby grants you the right to copy, modify, create derivative
works, redistribute, and make non-production use of the Licensed Work. The
Licensor may make an Additional Use Grant, above, permitting limited
production use.

Effective on the Change Date, or the fourth anniversary of the first publicly
available distribution of a specific version of the Licensed Work under this
License, whichever comes first, the Licensor hereby grants you rights under
the terms of the Change License, as specified in the Change License section
below.

1. Definitions

Capitalized terms in this license shall have the following meanings:

a. "Additional Use Grant" means a grant by the Licensor permitting you
   limited production use of the Licensed Work.

b. "Change Date" means the latest date on which you exercise your rights
   under this License to make non-production use of the Licensed Work.

c. "Change License" means the license that governs the Licensed Work on
   the Change Date.

d. "Licensed Work" means the original version of the software made
   available under this license.

e. "Licensor" means the individual or entity that offers the Licensed Work
   under the Business Source License.

f. "Non-production Use" means internal use, personal use, academic use,
   research use, evaluation use, testing use, and any use not for
   commercial gain or competitive advantage.

g. "Production Use" means use for commercial gain or competitive advantage,
   including use in connection with a commercial product or service that is
   sold, leased, rented, or otherwise made available for commercial gain
   or competitive advantage.

2. License Grants

a. Non-production Use Grant. Subject to the terms and conditions of this
   License, the Licensor hereby grants to you a non-exclusive, worldwide,
   royalty-free license to reproduce, prepare derivative works of, publicly
   display, publicly perform, sublicense, and distribute the Licensed Work and
   such derivative works in Source or Object form, for Non-production Use only.

b. No Production Use Grant. You may not make Production Use of the Licensed
   Work without an Additional Use Grant from the Licensor.

3. Redistribution

a. You may reproduce and distribute copies of the Licensed Work or
   Derivative Works thereof in any medium, with or without modifications,
   and in Source or Object form, provided that You meet the following
   conditions:

   (i) You must give any other recipients of the Licensed Work or
       Derivative Works a copy of this License;

   (ii) You must cause any modified files to carry prominent notices stating
       that You changed the files;

   (iii) You must retain, in the Source form of any Derivative Works that
       You distribute, all copyright, patent, trademark, and attribution
       notices from the Source form of the Licensed Work, excluding those
       notices that do not pertain to any part of the Derivative Works; and

   (iv) If the Licensed Work includes a "NOTICE" text file as part of its
       distribution, then any Derivative Works that You distribute must
       include a readable copy of the attribution notices contained within
       such NOTICE file, excluding those notices that do not pertain to any
       part of the Derivative Works, in at least one of the following places:
       within a NOTICE text file distributed as part of the Derivative Works;
       within the Source form or documentation, if provided along with the
       Derivative Works; or, within a display generated by the Derivative
       Works, if and wherever such third-party notices normally appear. The
       contents of the NOTICE file are for informational purposes only and do
       not modify the License. You may add Your own attribution notices within
       Derivative Works that You distribute, alongside or as an addendum to
       the NOTICE text from the Licensed Work, provided that such additional
       attribution notices cannot be construed as modifying the License.

b. You may add Your own copyright statement to Your modifications and may
   provide additional or different license terms and conditions for use,
   reproduction, or distribution of Your modifications, or for any such
   Derivative Works as a whole, provided Your use, reproduction, and
   distribution of the Licensed Work otherwise complies with the conditions
   stated in this License.

4. Trademarks

This License does not grant permission to use the trade names, trademarks,
service marks, or product names of the Licensor, except as required for
reasonable and customary use in describing the origin of the Licensed Work and
reproducing the content of the NOTICE file.

5. Disclaimer of Warranty

Unless required by applicable law or agreed to in writing, Licensor provides
the Licensed Work (and each Contributor provides its Contributions) on an "AS
IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied, including, without limitation, any warranties or conditions of TITLE,
NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You
are solely responsible for determining the appropriateness of using or
redistributing the Licensed Work and assume any risks associated with Your
exercise of permissions under this License.

6. Limitation of Liability

In no event and under no legal theory, whether in tort (including
negligence), contract, or otherwise, unless required by applicable law (such
as deliberate and grossly negligent acts) or agreed to in writing, shall any
Contributor be liable to You for damages, including any direct, indirect,
special, incidental, or consequential damages of any character arising as a
result of this License or out of the use or inability to use the Licensed
Work (including but not limited to damages for loss of goodwill, work
stoppage, computer failure or malfunction, or any and all other commercial
damages or losses), even if such Contributor has been advised of the
possibility of such damages.

7. Change License

a. Effective on the Change Date, the Licensed Work shall be made available
   under the following license: Apache License, Version 2.0.

b. The Change Date for this Licensed Work is January 1, 2029.

8. Additional Use Grant

a. You may make Production Use of the Licensed Work if you obtain a
   commercial license from the Licensor.

b. To inquire about a commercial license, please create a GitHub issue at:
   https://github.com/defenseunicorns/leapfrogai/issues/new/choose

c. In your issue, please include:
   - Your organization name
   - Contact information
   - Intended use case
   - Scale of deployment
   - Any other relevant details

9. Accepting Warranty or Additional Liability

While redistributing the Licensed Work or Derivative Works thereof, You may
choose to offer, and charge a fee for, acceptance of support, warranty,
indemnity, or other liability obligations and/or rights consistent with this
License. However, in accepting such obligations, You may act only on Your own
behalf and on Your sole responsibility, not on behalf of any other
Contributor, and only if You agree to indemnify, defend, and hold each
Contributor harmless for any liability incurred by, or claims asserted
against, such Contributor by reason of your accepting any such warranty or
additional liability.

END OF TERMS AND CONDITIONS

How to apply the Business Source License to your work:

To apply the Business Source License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "[]" replaced
with your own identifying information. (Don't include the brackets!)

Copyright 2025 CowabungaAI

Licensed under the Business Source License 1.1 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://mariadb.com/bsl11/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Change Date: 2029-01-01

On the date above, in accordance with the Business Source License, use
of this software will be governed by the Apache License, Version 2.0.