api:
  image:
    repository: "ghcr.io/defenseunicorns/cowabungaai/cowabunga-api"
    tag: "###ZARF_CONST_IMAGE_VERSION###"

  expose: "###ZARF_VAR_EXPOSE_API###"

  env:
    - name: COWABUNGA_LOG_LEVEL
      value: "INFO"
    - name: COWABUNGA_CONFIG_PATH
      value: /config/
    - name: COWABUNGA_CONFIG_FILENAME
      value: "*.toml"
    - name: DEFAULT_EMBEDDINGS_MODEL
      value: "###ZARF_VAR_DEFAULT_EMBEDDINGS_MODEL###"
    - name: DEV
      value: "###ZARF_VAR_DEV###"
    - name: PORT
      value: "8080"
    - name: TURSO_URL
      value: "http://turso.cowabungaai.svc.cluster.local:8080"
    - name: TURSO_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: turso-auth
          key: token
          optional: true

  migration:
    image:
      repository: "ghcr.io/defenseunicorns/cowabungaai/api-migrations"
      tag: "###ZARF_CONST_IMAGE_VERSION###"

kiwigrid:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: "1.23.3"
