name: setup-lfai-core
description: "Setup Turso and LFAI-API"

runs:
  using: composite
  steps:
    - name: Deploy Turso
      shell: bash
      run: |
        make build-turso LOCAL_VERSION=e2e-test
        docker image prune -af
        uds zarf tools kubectl create namespace leapfrogai
        uds zarf package deploy packages/turso/zarf-package-turso-amd64-e2e-test.tar.zst --confirm
        rm packages/turso/zarf-package-turso-amd64-e2e-test.tar.zst

    - name: Deploy LFAI-API
      shell: bash
      run: |
        make build-api LOCAL_VERSION=e2e-test FLAVOR=upstream
        docker image prune -af
        uds zarf package deploy packages/api/zarf-package-leapfrogai-api-amd64-e2e-test.tar.zst --confirm
        rm packages/api/zarf-package-leapfrogai-api-amd64-e2e-test.tar.zst
