{{- if .Values.turso.auth.enabled }}
{{- if and (not .Values.turso.auth.existingSecret) .Values.turso.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turso.fullname" . }}-auth
  labels:
    {{- include "turso.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.turso.auth.token }}
{{- end }}
{{- end }}
