name: lint
on: [pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Lint
        uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1.0.0
        with:
          version: 0.3.4

      - name: Validate Formatting
        uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1.0.0
        with:
          version: 0.3.4
          args: format --check

      # Javascript & Typescript Linting
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install UI Dependencies
        run: npm --prefix src/leapfrogai_ui install

      - name: Run UI Linter
        run: npm --prefix src/leapfrogai_ui run lint
