name: ui-test
on:
  pull_request:
    paths:
      # Ignore all workflows except this one
      - ".github/workflows/ui-test.yaml"

      # LFAI-UI things (no Python)
      - "src/leapfrogai_ui/**"
      - "packages/ui/**"

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: uitest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit
